# Generated by Django 3.0.2 on 2020-01-23 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 9, 59, 8, 796777, tzinfo=utc)),
        ),
    ]
