# Generated by Django 3.0.2 on 2020-02-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200210_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_on']},
        ),
    ]
